### ISSUE TITLE
[Feature] Modularity for Bukkit/Spigot/Paper, Nukkit and others.

### ISSUE THREAD

**Issue by portlek** [MrNemo64/player-chat-inputs#4]
The project can separate for each minecraft server base system.

**Comment by MrNemo64** [comment]
Could you explain a little more?

**Comment by portlek** [comment]
I did that with my p.r. you can check it out.

**Comment by portlek** [comment]
like core, bukkit, nukkit modules. i separated these cases.

**Comment by MrNemo64** [comment]
This is beyond my understanding and I'm a new wn github on top so I'm messing around on two sides. Still thanks for the suggestions, I'll try to implement them and understand your code to improve

**Comment by portlek** [comment]
alright, np.

**Comment by PikaMug** [comment]
Please consider implementing this change. Having the ability to expand beyond the Bukkit platform would be a boon for this library.

**Comment by MrNemo64** [comment]
> Please consider implementing this change. Having the ability to expand beyond the Bukkit platform would be a boon for this library.

I have!
Right now I'm working on a 2.0 version, a better version. Right now this one just allows for chat input and not much more. Thats good in the sense that it's simple and easy to use but it has 2 main problems in my opinion:
1. Limited: First this project was called "PlayerInputs" although you could only get inputs via chat, I'd like to expand that option
2. Problematic: When developing this, a problem came to my mind: 'What if an input process is started when another one is running?' [My solution was to have a collection of players that were in an input process](https://github.com/MrNemo64/player-chat-inputs/blob/d164ae61ef9ef9d9b8c1bf521bb41b10a8f17586/src/main/java/me/nemo_64/spigotutilities/playerinputs/chatinput/PlayerChatInput.java#L305) (I didn't know much about sets at the time) but since this class is shadered/copy pasted into projects, if 2 projects with the class start an input process on the same player they will conflict, and well, I could use the Metadata API of spigot to mark the player and all of that but it only would work on spigot

My idea is to remake the API but allowing for more input types. Right now this is what I've thought:
1. An InputListener would collect an input (this may be via chat, inventory, sign...) and pass it to an InputProcessor
2. The InputProcessor would check if the input is the cancel input, if its a valid input and convert the input to the desired value type and notify an InputConsumer
3. The input consumer is notifyed of what kind of input was received (cancel input, invalid input, valid input, player disconnects, timer expires...) and based on that gives an InputResponse
4. The InputResponse is the processed by the InputProcess, if the response is FINALIZE_INPUT_PROCESS then the input process finishes, if the response is CONTINUE_INPUT_PROCESS we continue as normal, FAIL_INPUT_PROCESS we fail the process (maybe the cancel input was given)...
5. When the FINALIZE_INPUT_PROCESS is given, the input process subscribers get notified that the process finished and are given the final value

How is this any better? Well lets imagine this scenario: Lets say I want to ask the player for a material. I can create a `MaterialSelectorInputListener` that creates an inventory with all the materials and allows the player to click on one of them, when the user clicks on it the processor validates the material (in this case, most likelly all materials are valid) and notifies the input consumer about the clicked material. Then the consumer finalizes the project with the selected material.
Want to be able to select 3 materials? No problem! Just store the first and second material and give the "CONTINUE" response and when the third one is given finalize the input process
(I will say the _select 3 materials_ way is kinda inposible right now but working on solving it)
Because of the complexity of this, creating a process will be harder. Ideally the API will come with predefined and tested listeners, processors and consumers so you can combine them for whatever you need, kinda like a modular system
But there are several classes and the API makes your plugin bigger, and we still have the problem of "What if its shadered in the project". This is why I've thought about posting this API to the Treasury project. Since the API would be in an external plugin you wouldnt need to shade it and we solve both problems with the inconvenient of depending on another plugin but since Treasury aims to provide a collection of APIs (like an economy one, aimed to replace Vault, and some other that are in development like a Protections API) I expect it to be on most servers.
What if the API isn't accepted into Treasury? I'll think about that if happens

See the classes here, any kind of early feedback is apreciated!
https://github.com/MrNemo64/Treasury/tree/feat/player-inputs/api/src/main/java/me/lokka30/treasury/api/player_inputs

**Comment by PikaMug** [comment]
I suspect the Bukkit Conversation API only permits one conversation at a time (as I know there's a `Conversable#isConversing` method) but either way one might check to see how they've addressed the concern. You might also consider storage I/O.

My concern with a PR is that Treasury is not widely adopted. Not to say it would hurt, but if shading weren't the goal I'd rather see PlayerInputs packaged as a plugin for dependency instead (or in addition to its inclusion in Treasury).

Side note: Consider allowing multi-consumer input using an [Audience](https://docs.adventure.kyori.net/audiences.html) from Kyori Adventure.

**Comment by portlek** [comment]
i did it already. you guys can find here:
https://github.com/Infumia/InfumiaLib/tree/master/shared/src/main/java/tr/com/infumia/infumialib/input

and here:
https://github.com/Infumia/InfumiaLib/tree/master/platform/paper/api/src/main/java/tr/com/infumia/infumialib/platform/paper/input

**Comment by MrNemo64** [comment]
> I suspect the Bukkit Conversation API only permits one conversation at a time (as I know there's a Conversable#isConversing method) but either way one might check to see how they've addressed the concern. You might also consider storage I/O.

Each player has an instance of [ConversationTraker ](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/conversations/ConversationTracker.java)which manages the players conversations
I hadn't considered I/O but I don't know if I like the idea. I'll give it some thought

> My concern with a PR is that Treasury is not widely adopted. Not to say it would hurt, but if shading weren't the goal I'd rather see PlayerInputs packaged as a plugin for dependency instead (or in addition to its inclusion in Treasury).

I'm trying to make Treasury more popular as I belive that is an important step in the right direction, but maybe I should make both, PR and stand alone plugin
I think I'll continue developing on my own stand alone and when finished I'll message the Treasury team to maybe include the API

> Side note: Consider allowing multi-consumer input using an [Audience](https://docs.adventure.kyori.net/audiences.html) from Kyori Adventure.

I didn't know about this but I don't really see how to implement it. You mean, for example, an input process that asks for a number and automatically updates a boss bar?

And as @portlek said, he added cross platform for the API and I'm gratefull for it but at the time I didn't know enough to merge and I didn't like the idea of supporting code that I dont understand, you may use their version :D

**Comment by PikaMug** [comment]
No, an Audience is a group of consumers that would receive the same conversation. You could, for example, update one conversation for all users based on individual input. Regardless, the real advantage is the [platform support](https://docs.adventure.kyori.net/platform/index.html).

I get that you're hesitant to go cross-platform but urge you to see this as a learning opportunity instead of an obstacle.

**Comment by MrNemo64** [comment]
> No, an Audience is a group of consumers that would receive the same conversation. You could, for example, update one conversation for all users based on individual input. Regardless, the real advantage is the [platform support](https://docs.adventure.kyori.net/platform/index.html).
> 
> I get that you're hesitant to go cross-platform but urge you to see this as a learning opportunity instead of an obstacle.

I think I get you. Anyway cross platform is something that I'll try to implement. Thanks for your help!

**Comment by MrNemo64** [comment]
> > Please consider implementing this change. Having the ability to expand beyond the Bukkit platform would be a boon for this library.
> 
> I have! Right now I'm working on a 2.0 version, a better version.

Remember this? 
The idea has changed quite a lot. 
I am planing on posting this on the spigot forums but I thought I would first share it to some people to get ideas on what may be explained wrong or what is confusing. Since you showed intrest on this, if you have time and want to, could you check it out?
https://github.com/MrNemo64/better-inputs/
You may just talk about it here or talk to me on discord Nemo_64#6164 (if you want and can)

**Comment by PikaMug** [comment]
> https://github.com/MrNemo64/better-inputs/

Great to see you have the abstraction mindset but I see no point in posting it there as there are no Minecraft-centric modules. I'm also not personally interested in contributing until #3 has been merged or implemented in either project, per the issue topic.

**Comment by MrNemo64** [comment]
> > https://github.com/MrNemo64/better-inputs/
> 
> Great to see you have the abstraction mindset but I see no point in posting it there as there are no Minecraft-centric modules. I'm also not personally interested in contributing until #3 has been merged or implemented in either project, per the issue topic.

There arent any Minecraft-centric modules because this is a prof of concept but I can make a Spigot one before posting without problem. All the issues mentioned in #3 will eventually be addressed
